version: '3'

services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        networks:
            - app-network
    server-api:
        build: ./server
        ports: 
            - "4000:4000"
        environment:
            - DATABASE_HOST=db
            - DATABASE_NAME=so-final
            - DATABASE_PORT=27017
            - IS_DOCKERIZED=true
        networks:
            - app-network
        links:
            - db
        restart: on-failure
    react-client:
        build: ./client
        ports:
            - "80:80"
volumes:
    mongodata: {}

networks:
    app-network:
        driver: bridge